import warnings
import pandas as pd
import numpy as np

from ..utils.verbose_print import verbose_init
from ..utils.misc import Container, DataAttr, rgetattr, rsetattr, multiply_aligned
from ..utils.retriever import ParameterRetriever

ixsl = pd.IndexSlice

class DemandAndConversions(object):
    '''Class that calculates demand for domestic and imported crop and animal products, as well as generated food waste
    and by-products etc. A per capita diet is defined in the parameter Excel sheet along with parmeters for import shares,
    conversion factors, waste levels, etc.

    Parameters
    ----------
    par : ParameterRetriever object

    Attributes set on init
    ----------------------
    None

    Attributes set by FoodDemand.calculate()
    ----------------------------------------
    population : int [millions]
    food_demand : pandas.DataFrame [kg/year]
        Demand for food per production system and origin (domestic, imported)
    food_demand_to_processing : pandas.DataFrame [kg/year]
        Food demand after accounting for household, retail and processing wastes
    crop_prod_demand : pandas.DataFrame
    crop_by_products : pandas.DataFrame
    animal_prod_demand : pandas.DataFrame
    animal_by_products : pandas.DataFrame
    waste : pandas.DataFrame [kg/year]
        Generated waste at household, retail and processing. Only includes domestically
        generated waste assuming that processing waste for imported foods occur abroad.
    '''

    module_name = 'DemandAndConversions'

    def __init__(self, par: ParameterRetriever):

        # Set to keep track of data attributes that have been assigned
        self.data_attr = DataAttr(self)

        self.par = par

    def calculate(self, verbose=False):
        '''Calculate crop and animal product demand and generated by-products and waste
        
        Parameters
        ----------
        verbose : Bool
            Whether or not to print progress messages
            
        Returns
        -------
        Nothing. Stores output in pandas.DataFrames in the attrubutes:
        'food_demand', 'crop_prod_demand', 'animal_prod_demand', 'by_products' and 'waste'
        '''

        # Define functions to print progress messages if verbose==True
        vprint = verbose_init(verbose, id_str='DemandAndConversions')

        # Get population size
        self.get_population()

        # Calculate total food demand [kg/year]
        vprint('Calculating food demand ...')
        self.calculate_food_demand()

        # Calculate generated food waste [kg/year]
        vprint('Calculating waste ...')
        self.calculate_waste()

        # Calculate demand for crop products and generated crop by-products
        vprint('Calculating crop product demand ...')
        self.get_non_food_and_export_demand()
        self.calculate_crop_product_demand()

        # Calculate demand for animal products and generated animal by-products
        vprint('Calculating animal product demand ...')
        self.calculate_animal_product_demand()

        vprint(type='end')

    def make_static(self):
        '''Returns a StaticDemandAndConversions object that retains all data attributes but
        has no methods or ParameterRetriever'''
        
        obj = StaticDemandAndConversions()

        obj.data_attr = DataAttr(obj)

        for attr in self.data_attr:
            if rgetattr(self, attr) is not None:
                obj.data_attr.add(data=rgetattr(self, attr).copy(), name=attr, **self.data_attr[attr])
            else:
                obj.data_attr.add(data=None, name=attr, **self.data_attr[attr])

        return obj

    def get_population(self):

        self.par.clear()

        population = self.par.get('population')[0]

        # Add data attribute
        self.data_attr.add(
            population,
            name = 'population',
            unit = 'millions',
            orig = 'DemandAndConversions',
            desc = 'Human population'
        )

    def calculate_food_demand(self):

        self.par.clear()
        
        # Get food items included in the diet and included production systems
        fs = self.par.get_unique(['food','food_group'], 'parameter == "consumption"')
        pss = self.par.get_unique('prod_system', 'parameter == "share_in_prod_system"')

        # Create dataframe for domestic and imported food demand ('food_demand')
        food_demand = pd.DataFrame(
            columns=pd.Index(['domestic','imported'],name='origin'),
            index=pd.MultiIndex.from_tuples(
                [(f,fg,ps) for f,fg in fs.values for ps in pss],
                names=['food','food_group','prod_system']
            )
        )

        # Get shares per production system
        share_per_prod_system = self.par.get_from_frame('share_in_prod_system',food_demand)/100
        # Calculate share conventional as what remains (Note: important that 'share_in_prod_system' == -100 in parameter Excel sheet)
        share_con = share_per_prod_system.xs('conventional', level='prod_system', drop_level=False)
        share_con = (share_per_prod_system.groupby('food').sum() * -1).reindex(share_con.index, level='food')
        share_per_prod_system.update(share_con)

        # Get shares per origin
        share_per_origin = self.par.get_from_frame('share_imported',food_demand)/100
        share_per_origin.loc[:,'domestic'] = 1 - share_per_origin.loc[:,'imported']

        # Get consumption (g/day)
        cons = self.par.get_from_frame('consumption',food_demand) * share_per_prod_system * share_per_origin

        # Add data attribute
        self.data_attr.add(
            # Convert to [kg/year] and factor in population
            cons / 1000 * 365.25 * self.population * 1000000,
            name = 'food_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for food per production system and origin (domestic, imported)'
        )

    def calculate_waste(self):

        self.par.clear()
        
        # Get shares wasted at different levels
        waste_shares = pd.DataFrame(
            columns = pd.Index(['household','retail','processing'], name='waste_level'),
            index = self.food_demand.index
        )

        waste_shares = self.par.get_from_frame('waste_share',waste_shares)/100

        # Apply waste shares and calculate food needed to enter each stage
        food_to_household = self.food_demand.mul(1/(1-waste_shares['household']),axis=0)
        food_to_retail = food_to_household.mul(1/(1-waste_shares['retail']),axis=0)
        food_to_processing = food_to_retail.mul(1/(1-waste_shares['processing']),axis=0)

        # Create waste dataframe
        waste = pd.DataFrame(
            columns=waste_shares.columns,
            index=waste_shares.index
        )

        # Calculate waste at each stage
        # Processing waste for imported foods is assumed to be generated abroad (i.e. not included)
        waste['household'] = (food_to_household - self.food_demand).sum(axis=1)
        waste['retail'] = (food_to_retail - food_to_household).sum(axis=1)
        waste['processing'] = food_to_processing['domestic'] - food_to_retail['domestic'] 
        # waste = waste.droplevel('food_group')

        # Add data attributes
        self.data_attr.add(
            food_to_processing,
            name = 'food_demand_to_processing',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Food demand after accounting for household, retail and processing wastes'
        )
        self.data_attr.add(
            waste,
            name = 'waste',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Household, retail and processing wastes'
        )

    def get_non_food_and_export_demand(self):

        self.par.clear()

        # Get food items and production systems with non-food demand 
        fs_pss = self.par.get_unique(
            ['food','food_group','prod_system'],
            'parameter == "non_food_demand"'
        )

        # Create dataframe for non-food demand
        non_food_demand = pd.Series(
            index=pd.MultiIndex.from_tuples(
                [(f,fg,ps) for f,fg,ps in fs_pss.values],
                names=['food','food_group','prod_system']
            ),
            dtype = float
        )

        # Get food items and production systems with export demand 
        fs_pss = self.par.get_unique(
            ['food','food_group','prod_system'],
            'parameter == "export_demand"'
        )

        # Create dataframe for export demand
        export_demand = pd.Series(
            index=pd.MultiIndex.from_tuples(
                [(f,fg,ps) for f,fg,ps in fs_pss.values],
                names=['food','food_group','prod_system']
            ),
            dtype = float
        )

        # Get non-food and export demand
        non_food_demand.loc[:] = self.par.get('non_food_demand',**non_food_demand.index.to_frame().to_dict('list')) * 1000
        export_demand.loc[:] = self.par.get('export_demand',**export_demand.index.to_frame().to_dict('list')) * 1000

        # Add data attributes
        self.data_attr.add(
            non_food_demand,
            name = 'non_food_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for non-food uses'
        )
        self.data_attr.add(
            export_demand,
            name = 'export_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for exports'
        )
        

    def calculate_crop_product_demand(self):

        self.par.clear()
        
        # Get demand for food + non-food
        demand = pd.concat((
            self.food_demand_to_processing['domestic'].rename('food'),
            self.non_food_demand.rename('non-food'),
            self.export_demand.rename('export')
        ), axis=1).rename_axis('demand',axis=1)

        # Get crop products and by-products
        cps = self.par.get_unique('crop_prod','parameter == "conv_factor_main"')
        bps = self.par.get_unique(['crop_prod','by_prod'],'parameter == "conv_factor_by"')

        crop_prod_demand = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(d,cp) for d in demand.columns for cp in cps ],
                names=['demand','crop_prod']
            ),
            index = demand.index
        )

        # Create dataframe for generated by-products
        crop_by_products = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(d,cp,bp) for d in demand.columns for cp,bp in bps.values],
                names=['demand','crop_prod','by_prod']
            ),
            index = demand.index
        )

        # Get conversion factors. 0 are replaced with NaN to avoid div by 0
        # NaNs are later replaced with 0s
        CF_crop_prod = (self.par.get_from_frame('conv_factor_main', crop_prod_demand)/100).replace({0:np.nan})
        CF_by_prod = (self.par.get_from_frame('conv_factor_by', crop_by_products)/100).replace({0:np.nan})

        # Calculate demand for crop products and generated by-products
        crop_prod_demand = multiply_aligned((1/CF_crop_prod),demand)
        crop_by_products = multiply_aligned((CF_by_prod),crop_prod_demand)

        # Aggregate
        crop_prod_demand = crop_prod_demand.stack('crop_prod').groupby(['prod_system','crop_prod']).sum()
        crop_by_products = crop_by_products.stack(['crop_prod','by_prod']).groupby(['prod_system','crop_prod','by_prod']).sum()

        # Add data attributes
        self.data_attr.add(
            crop_prod_demand,
            name = 'crop_prod_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for crop products'
        )
        self.data_attr.add(
            crop_by_products,
            name = 'crop_by_products',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Generated crop by-products'
        )

    def calculate_animal_product_demand(self):

        self.par.clear()

        # Get demand for food + non-food
        demand = pd.concat((
            self.food_demand_to_processing['domestic'].rename('food'),
            self.non_food_demand.rename('non-food'),
            self.export_demand.rename('export')
        ), axis=1).rename_axis('demand',axis=1)

        # Get animal products and by-products
        aps = self.par.get_unique(['species','animal_prod'],'parameter == "conv_factor_main" & ~f_species.isna()')
        bps = self.par.get_unique(['species','animal_prod','by_prod'],'parameter == "conv_factor_by"')

        # Create dataframe for animal product demand
        animal_prod_demand = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(d,sp,ap) for d in demand.columns for sp,ap in aps.values],
                names=['demand','species','animal_prod']
            ),
            index = demand.index
        )

        # Create dataframe for generated by-products
        animal_by_products = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(d,sp,ap,bp) for d in demand.columns for sp,ap,bp in bps.values],
                names=['demand','species','animal_prod','by_prod']
            ),
            index = demand.index
        )

        # Get conversion factors. 0 are replaced with NaN to avoid div by 0
        # NaNs are later replaced with 0s
        CF_animal_prod = (self.par.get_from_frame('conv_factor_main', animal_prod_demand)/100).replace({0:np.nan})
        CF_by_prod = (self.par.get_from_frame('conv_factor_by', animal_by_products)/100).replace({0:np.nan})

        # Calculate demand for animal products and generated by-products
        # animal_prod_demand = (1 / CF_animal_prod).mul(self.food_demand_to_processing['domestic'], axis=0).fillna(0)
        # animal_by_products = (CF_by_prod).mul(self.food_demand_to_processing['domestic'], axis=0).fillna(0)

        animal_prod_demand = multiply_aligned((1/CF_animal_prod),demand)
        animal_by_products = multiply_aligned((CF_by_prod),animal_prod_demand)

        # Aggregate
        animal_prod_demand = animal_prod_demand.stack(['species','animal_prod']).groupby(['prod_system','species','animal_prod']).sum()
        animal_by_products = animal_by_products.stack(['species','animal_prod','by_prod']).groupby(['prod_system','species','animal_prod','by_prod']).sum()

        # Handle dairy "cream balance". As consumption of high fat dairy products and associated demand for cream exceeds
        # the ammount of cream generated from consumption of low fat dairy products this induces an export of low fat
        # dairy products.
        #
        # Note: The method currently implemented will fail to handle a situation where the opposite is true, i.e. where
        # consumption of low fat products generates more cream than needed to cover consumption of high fat products.
        self.par.clear()
        indeuce_export_of = 'Milk and products 1-2% fat'
        cream_to_raw_milk = 1/(self.par.get(
            'conv_factor_by',
            food=indeuce_export_of,
            species='cattle',
            animal_prod='milk',
            by_prod='cream'
        )[0]/100)

        self.par.clear()
        raw_milk_to_skim_milk = self.par.get(
            'conv_factor_main',
            food=indeuce_export_of,
            species='cattle',
            animal_prod='milk'
        )[0]/100

        # Calculate shortage of cream to satisfy demand for fat rich products
        cream_shortage = \
        animal_prod_demand.loc[(slice(None),'cattle','cream')] - \
        animal_by_products.loc[(slice(None),'cattle','milk','cream')]

        # Calculate additional raw milk that needs to be produced and induced skim milk exports
        add_raw_milk_prod = cream_shortage * cream_to_raw_milk
        induced_skim_milk_exports = (add_raw_milk_prod * raw_milk_to_skim_milk).sum(axis=1)

        # Add additional raw milk production to demand dataframe
        for ps in animal_prod_demand.index.get_level_values('prod_system').unique():
            animal_prod_demand.loc[(ps,'cattle','milk')] = \
            animal_prod_demand.loc[(ps,'cattle','milk')] + \
            add_raw_milk_prod.loc[ps]

        # The "cream balance" is now handled. So, drop cream from demand and generated by-products
        animal_prod_demand = animal_prod_demand[animal_prod_demand.index.get_level_values('animal_prod') != 'cream']
        animal_by_products = animal_by_products[animal_by_products.index.get_level_values('by_prod')!='cream'].rename({'cream':'milk'})

        # Add data attributes
        self.data_attr.add(
            animal_prod_demand,
            name = 'animal_prod_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for animal products'
        )
        self.data_attr.add(
            animal_by_products,
            name = 'animal_by_products',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Generated animal by-products'
        )

        # Add induced skim milk exports to export demand
        self.export_demand = self.export_demand.add(
            pd.concat([
                pd.concat([
                        induced_skim_milk_exports
                ], keys=['export'], names=['food_group'])
            ], keys=[indeuce_export_of], names=['food']),
            fill_value=0
        )

        # Handle demand for animal by-products !!!

class StaticDemandAndConversions(Container):
    '''Class used to create static copy of DemandAndConversions object. These stores all attributes except 'par'
    but does not inherit any methods'''

    def __repr__(self):
        return DemandAndConversions.__repr__(self)