import warnings
import pandas as pd
import numpy as np

from ..utils.verbose_print import verbose_init
from ..utils.data_attr import DataAttr
from ..utils.misc import multiply_aligned
from ..utils.retriever import ParameterRetriever

ixsl = pd.IndexSlice

class DemandAndConversions(object):
    '''Class that calculates demand for domestic and imported crop and animal products, as well as generated food waste
    and by-products etc. A per capita diet is defined in the parameter Excel sheet along with parmeters for import shares,
    conversion factors, waste levels, etc.

    Parameters
    ----------
    par : ParameterRetriever object

    Attributes set on init
    ----------------------
    None

    Attributes set by FoodDemand.calculate()
    ----------------------------------------
    population : int [millions]
    food_demand : pandas.DataFrame [kg/year]
        Demand for food per production system and origin (domestic, imported)
    food_demand_to_processing : pandas.DataFrame [kg/year]
        Food demand after accounting for household, retail and processing wastes
    crop_prod_demand : pandas.DataFrame
    crop_by_products : pandas.DataFrame
    animal_prod_demand : pandas.DataFrame
    animal_by_products : pandas.DataFrame
    waste : pandas.DataFrame [kg/year]
        Generated waste at household, retail and processing. Only includes domestically
        generated waste assuming that processing waste for imported foods occur abroad.
    '''

    module_name = 'DemandAndConversions'

    def __init__(self, par: ParameterRetriever):

        # Set to keep track of data attributes that have been assigned
        self.data_attr = DataAttr(self)

        self.par = par

    def calculate(self, verbose=False):
        '''Calculate crop and animal product demand and generated by-products and waste
        
        Parameters
        ----------
        verbose : Bool
            Whether or not to print progress messages
            
        Returns
        -------
        Nothing. Stores output in pandas.DataFrames in the attrubutes:
        'food_demand', 'crop_prod_demand', 'animal_prod_demand', 'by_products' and 'waste'
        '''

        # Define functions to print progress messages if verbose==True
        vprint = verbose_init(verbose, id_str='DemandAndConversions')

        # Get population size
        self.get_population()

        # Calculate total food demand [kg/year]
        vprint('Calculating food demand ...')
        self.calculate_food_demand()
        self.get_non_food_and_export_demand()

        # Resolve food recipies
        vprint('Resolving recipies for compound foods ...')
        for at in ['food_demand', 'non_food_demand', 'export_demand']:
            self.resolve_recipies(at)

        # Calculate generated food waste [kg/year]
        vprint('Calculating waste ...')
        self.calculate_waste()

        # Calculate demand for crop and animal products, crop residues and by-products and calculate generated by-products
        vprint('Calculating product demand and generated by-products...')
        self.calculate_product_demand_and_by_products()

        vprint(type='end')

    def make_static(self):
        '''Returns a StaticDemandAndConversions object that retains all data attributes but
        has no methods or ParameterRetriever'''
        
        obj = StaticDemandAndConversions()

        obj.data_attr = DataAttr(obj)

        for attr in self.data_attr:
            if self.data_attr.get(attr) is not None:
                obj.data_attr.add(data=self.data_attr.get(attr).copy(), name=attr, **self.data_attr[attr])
            else:
                obj.data_attr.add(data=None, name=attr, **self.data_attr[attr])

        return obj

    def get_population(self):

        # Get total population
        population = self.par.get('population')[0]

        # Get population per region
        population_per_region = pd.Series(
            self.par.get('population_region', region = self.par.get_unique('region')),
            index = pd.Index(
                self.par.get_unique('region'),
                name = 'region'
            )
        )

        # Adjust population per region to match total population
        population_per_region = population_per_region / population_per_region.sum() * population * 1_000_000

        # Add data attributes
        self.data_attr.add(
            population,
            name = 'population',
            unit = 'millions',
            orig = 'DemandAndConversions',
            desc = 'Human population'
        )
        self.data_attr.add(
            population_per_region,
            name = 'population_per_region',
            unit = 'nr',
            orig = 'DemandAndConversions',
            desc = 'Human population per region'
        )

    def calculate_food_demand(self):

        self.par.clear()
        
        # Get food items included in the diet and included production systems
        fs = self.par.get_unique(['food','food_group'], 'parameter == "consumption"')
        pss = self.par.get_unique('prod_system', 'parameter == "share_in_prod_system"')

        # Create dataframe for domestic and imported food demand ('food_demand')
        food_demand = pd.DataFrame(
            columns=pd.Index(['domestic','imported'],name='origin'),
            index=pd.MultiIndex.from_tuples(
                [(f,fg,ps) for f,fg in fs.values for ps in pss],
                names=['food','food_group','prod_system']
            )
        )

        # Get shares per production system
        share_per_prod_system = self.par.get_from_frame('share_in_prod_system',food_demand)/100
        # Calculate share conventional as what remains (Note: important that 'share_in_prod_system' == -100 in parameter Excel sheet)
        share_con = share_per_prod_system.xs('conventional', level='prod_system', drop_level=False)
        share_con = (share_per_prod_system.groupby('food').sum() * -1).reindex(share_con.index, level='food')
        share_per_prod_system.update(share_con)

        # Get shares per origin
        share_per_origin = self.par.get_from_frame('share_imported',food_demand)/100
        share_per_origin.loc[:,'domestic'] = 1 - share_per_origin.loc[:,'imported']

        # Get consumption (g/day)
        cons = self.par.get_from_frame('consumption',food_demand) * share_per_prod_system * share_per_origin

        # Add data attribute
        self.data_attr.add(
            # Convert to [kg/year] and factor in population
            cons / 1000 * 365.25 * self.data_attr.get('population') * 1000000,
            name = 'food_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for food per production system and origin (domestic, imported)'
        )

    def calculate_waste(self):

        self.par.clear()
        
        # Get shares wasted at different levels
        waste_shares = pd.DataFrame(
            columns = pd.Index(['household','retail','processing'], name='waste_level'),
            index = self.data_attr.get('food_demand').index
        )

        waste_shares = self.par.get_from_frame('waste_share',waste_shares)/100

        # Apply waste shares and calculate food needed to enter each stage
        food_to_household = self.data_attr.get('food_demand').mul(1/(1-waste_shares['household']),axis=0)
        food_to_retail = food_to_household.mul(1/(1-waste_shares['retail']),axis=0)
        food_to_processing = food_to_retail.mul(1/(1-waste_shares['processing']),axis=0)

        # Create waste dataframe
        waste = pd.DataFrame(
            columns=waste_shares.columns,
            index=waste_shares.index
        )

        # Calculate waste at each stage
        # Processing waste for imported foods is assumed to be generated abroad (i.e. not included)
        waste['household'] = (food_to_household - self.data_attr.get('food_demand')).sum(axis=1)
        waste['retail'] = (food_to_retail - food_to_household).sum(axis=1)
        waste['processing'] = food_to_processing['domestic'] - food_to_retail['domestic'] 
        # waste = waste.droplevel('food_group')

        # Add data attributes
        self.data_attr.add(
            food_to_processing,
            name = 'food_demand_to_processing',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Food demand after accounting for household, retail and processing wastes'
        )
        self.data_attr.add(
            waste,
            name = 'waste',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Household, retail and processing wastes'
        )

    def get_non_food_and_export_demand(self):

        self.par.clear()

        # Get food items and production systems with non-food demand 
        fs_pss = self.par.get_unique(
            ['food','food_group','prod_system'],
            'parameter == "non_food_demand"'
        )

        # Create dataframe for non-food demand
        non_food_demand = pd.Series(
            index=pd.MultiIndex.from_tuples(
                [(f,fg,ps) for f,fg,ps in fs_pss.values],
                names=['food','food_group','prod_system']
            ),
            dtype = float
        )

        # Get food items and production systems with export demand 
        fs_pss = self.par.get_unique(
            ['food','food_group','prod_system'],
            'parameter == "export_demand"'
        )

        # Create dataframe for export demand
        export_demand = pd.Series(
            index=pd.MultiIndex.from_tuples(
                [(f,fg,ps) for f,fg,ps in fs_pss.values],
                names=['food','food_group','prod_system']
            ),
            dtype = float
        )

        # Get non-food and export demand
        non_food_demand.loc[:] = self.par.get('non_food_demand',**non_food_demand.index.to_frame().to_dict('list')) * 1000
        export_demand.loc[:] = self.par.get('export_demand',**export_demand.index.to_frame().to_dict('list')) * 1000

        # Make dataframes matching 'food_demand'
        non_food_demand = non_food_demand.to_frame().rename(columns={0:'domestic'}).rename_axis('origin', axis=1)
        non_food_demand['imported'] = 0
        export_demand = export_demand.to_frame().rename(columns={0:'domestic'}).rename_axis('origin', axis=1)
        export_demand['imported'] = 0

        # Add data attributes
        self.data_attr.add(
            non_food_demand,
            name = 'non_food_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for non-food uses'
        )
        self.data_attr.add(
            export_demand,
            name = 'export_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for exports'
        )
        
    def resolve_recipies(self, attr):
    
        # Get original df
        orig_df = self.data_attr.get(attr)
        
        # Get compound foods (i.e. foods defined by a recipie of food ingrediets)
        fos = self.par.get_unique('food', 'parameter == "recipie"')
        
        # Get food ingreadients
        try:
            fis = self.par.get_unique(['food','food_ingr'], 'parameter == "recipie"').set_index(['food','food_ingr'])
        except KeyError:
            # If 'food_ingr' not in columns do nothing 
            return None
        
        # Slice compound foods from original df
        resolved_df = orig_df.loc[orig_df.index.get_level_values('food').isin(fis.index.get_level_values('food'))]
        if len(resolved_df) == 0:
            return None
        
        # Add food ingredients as index
        resolved_df = resolved_df.join(fis).rename_axis('origin', axis=1)
        
        # Get recipies
        resolved_df = resolved_df * (self.par.get_from_frame('recipie', resolved_df)/100)
        # Resolve recipies
        resolved_df = (
            resolved_df
            .groupby(['food_ingr','food_group','prod_system'])
            .sum()
            .rename_axis(['food','food_group','prod_system'])
        )
        
        # Get food groups for the resolved ingrediets
        fgs = (
            self.par.get_unique(['food','food_group'])
            .set_index(['food'])
            # .loc[resolved_df.index.unique('food')]
        )
        # Take first food group if same food has been specified as several food groups
        fgs = fgs[~fgs.index.duplicated()]

        # Update food groups
        resolved_df = (
            resolved_df
            .join(fgs).rename_axis('origin', axis=1)
            .droplevel('food_group')
            .set_index('food_group', append=True)
            .reorder_levels(['food','food_group','prod_system'])
        )
        
        # Get import shares of resolved ingredients and redistribute domestic -> imported
        self.par.clear()
        imp_shares = self.par.get('share_imported', **resolved_df.index.to_frame().to_dict('list'))/100
        resolved_df.loc[:,'imported'] += resolved_df.loc[:,'domestic'] * imp_shares
        resolved_df.loc[:,'domestic'] *= (1-imp_shares)
        
        # Append resolved recipies and drop compound foods
        res_df = (
            pd.concat([
                orig_df.loc[~orig_df.index.get_level_values('food').isin(fos)],
                resolved_df
            ])
            .groupby(['food','food_group','prod_system'])
            .sum()
        )

        # Update data
        self.data_attr.update(attr, res_df)
        
        return None

    def calculate_product_demand_and_by_products(self):

        self.par.clear()
        
        # Get demand for food + non-food + exports
        demand = pd.concat((
            self.data_attr.get('food_demand_to_processing')['domestic'].rename('food'),
            self.data_attr.get('non_food_demand')['domestic'].rename('non-food'),
            self.data_attr.get('export_demand')['domestic'].rename('export')
        ), axis=1).rename_axis('demand',axis=1)

        # Calculate demand for crop and animal products, crop residues and by-products
        # and calculate generated by-products
        crop_prod_demand, crop_by_products = _get_demand(self, demand, 'crop_prod')
        animal_prod_demand, animal_by_products =_get_demand(self, demand, ['species','animal_prod'])
        crop_resid_demand, crop_resid_by_products = _get_demand(self, demand, 'crop_resid')
        by_prod_demand, by_prod_by_products = _get_demand(self, demand, 'by_prod')

        # Handle "cream balance" by inducing skim milk exports
        animal_prod_demand, animal_by_products = \
            _fix_cream_balance(self, animal_prod_demand, animal_by_products)

        # Combine dataframes of generated by-products
        by_products = (
            crop_by_products
            .add(animal_by_products, fill_value=0)
            .add(crop_resid_by_products, fill_value=0)
            .add(by_prod_by_products, fill_value=0)
        ).sum(axis=1)

        # Add data attributes
        self.data_attr.add(
            crop_prod_demand,
            name = 'crop_prod_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for crop products'
        )
        self.data_attr.add(
            animal_prod_demand,
            name = 'animal_prod_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for animal products'
        )
        self.data_attr.add(
            crop_resid_demand,
            name = 'crop_resid_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for crop residues'
        )
        self.data_attr.add(
            by_prod_demand,
            name = 'by_prod_demand',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Demand for by-products'
        )
        self.data_attr.add(
            by_products,
            name = 'by_products',
            unit = 'kg/year',
            orig = 'DemandAndConversions',
            desc = 'Generated by-products'
        )

class StaticDemandAndConversions():
    '''Class used to create static copy of DemandAndConversions object. These stores all attributes except 'par'
    but does not inherit any methods'''

    def __repr__(self):
        return DemandAndConversions.__repr__(self)
    
def _get_demand(self, demand, of):

    if isinstance(of, str):
        of = [of]
    
    # Get products in demand
    try:
        prs = self.par.get_unique(['food']+of,'parameter == "conv_factor_main"').set_index('food')
    except KeyError:
        # If <of> not in the columns return empty dfs
        return _empty_demand(demand, of)
    
    # Check for only one 'conv_factor_main' per 'food'
    # NOTE: Might be a good idea to make it possible to have compound 'food' items
    # but will likely require a rethink of how the conversion factors are defined...
    if not prs.index.is_unique:
        dups = prs.index.duplicated()
        raise ValueError(f"\nOne 'food' item can only be supplied by a single main product at the moment.\nMake sure only one 'conv_factor_main' is supplied for 'food' item(s):\n{dups}")
    
    # Get generated by-products
    bps = self.par.get_unique(['food', 'by_prod'],'parameter == "conv_factor_by"').set_index('food')
    
    # Construct dataframe for product demand, get conversion factors and calculate demand
    prod_demand = (
        demand.join(prs)
        .set_index(of, append=True)
        .rename_axis(columns='demand')
    )
    try:
        CF_main = (self.par.get_from_frame('conv_factor_main', prod_demand)/100).replace({0:np.nan})
    except ValueError:
        # If prod_demand is empty return empty dfs
        return _empty_demand(demand, of)
    prod_demand = (prod_demand * (1/CF_main)).dropna(how='all')
    
    # Custruct dataframe, get conversion factors and calculate by-products generated
    if not of[0] == 'by_prod':
        by_prod = (
            prod_demand.join(prs.join(bps).set_index(of, append=True))
            .set_index('by_prod', append=True)
            .rename_axis(columns='demand')
        )
    else:
        # Rename index level for the by-products in demand to avoid name conflict
        # with generated by-products
        by_prod = (
            prod_demand.rename_axis(index={'by_prod':'by_prod_main'})
            .join(prs.join(bps, lsuffix='_main').set_index('by_prod_main', append=True))
            .set_index('by_prod', append=True)
            .rename_axis(columns='demand')
        )
    try:
        CF_by = (self.par.get_from_frame('conv_factor_by', by_prod)/100).replace({0:np.nan})
    except ValueError:
        # If prod_demand is empty return empty dfs
        return _empty_demand(demand, of)
    by_prod = (by_prod * CF_by).dropna(how='all')
    
    # Aggregate
    prod_demand = prod_demand.groupby(['prod_system']+of).sum()
    by_prod = by_prod.groupby(['prod_system', 'by_prod']).sum()

    return (prod_demand, by_prod)

def _empty_demand(demand, of):
    # Returns empty demand and by-product dataframes
    prod_demand = pd.DataFrame(
        index = pd.MultiIndex.from_tuples([], names=['prod_system']+of),
        columns = demand.columns
    )
    by_prod = pd.DataFrame(
        index = pd.MultiIndex.from_tuples([], names=['prod_system', 'by_prod']),
        columns = demand.columns
    )
    return (prod_demand, by_prod)

def _fix_cream_balance(self, animal_prod_demand, animal_by_products, induce_export_of = 'Milk and products 1-2% fat'):
    # Handle dairy "cream balance". As consumption of high fat dairy products and associated demand for cream exceeds
    # the ammount of cream generated from consumption of low fat dairy products this induces an export of low fat
    # dairy products.
    #
    # Note: The method currently implemented will fail to handle a situation where the opposite is true, i.e. where
    # consumption of low fat products generates more cream than needed to cover consumption of high fat products.
    self.par.clear()

    # Get food group name of skim milk
    food_group = self.par.get_unique('food_group', 'f_food=="Milk and products 1-2% fat"')[0]

    cream_to_raw_milk = 1/(self.par.get(
        'conv_factor_by',
        food=induce_export_of,
        species='cattle',
        animal_prod='milk',
        by_prod='cream'
    )[0]/100)
    
    self.par.clear()
    raw_milk_to_skim_milk = self.par.get(
        'conv_factor_main',
        food=induce_export_of,
        species='cattle',
        animal_prod='milk'
    )[0]/100
    
    # Calculate shortage of cream to satisfy demand for fat rich products
    cream_shortage = \
    animal_prod_demand.xs(('cattle','cream'), level=('species','animal_prod')).sum(axis=1) - \
    animal_by_products.xs('cream', level='by_prod').sum(axis=1)
    
    # Calculate additional raw milk that needs to be produced and induced skim milk exports
    add_raw_milk_prod = cream_shortage * cream_to_raw_milk
    induced_skim_milk_exports = (add_raw_milk_prod * raw_milk_to_skim_milk)

    if (induced_skim_milk_exports<0).any():
        warnings.warn('DemandAndConversions: Adjusting the "cream balance" resulted in a negative export of skim milk, which \
will result in the GeoDistributor failing. This is because demand for low-fat dairy products generates \
more cream than demanded by high-fat dairy products. This situation can`t be handled currently and demand \
data need to be adjusted manually to avoid this situation.')
    
    # Add additional raw milk production to demand dataframe
    for ps in animal_prod_demand.index.get_level_values('prod_system').unique():
        animal_prod_demand.loc[(ps,'cattle','milk'), 'export'] = \
        animal_prod_demand.loc[(ps,'cattle','milk'), 'export'] + \
        add_raw_milk_prod.loc[ps]

    # Create dataframe to add to export deamnd
    df_to_add = pd.concat([
        pd.concat([
                induced_skim_milk_exports.to_frame()
                .rename(columns={0:'domestic'})
                .rename_axis('origin', axis=1)
        ], keys=[food_group], names=['food_group'])
    ], keys=[induce_export_of], names=['food'])
    df_to_add['imported'] = 0

    # Add induced skim milk exports to export demand
    self.data_attr.update(
        'export_demand',
        self.data_attr.get('export_demand')
        .add(df_to_add, fill_value=0)
    )
    
    # The "cream balance" is now handled. So, drop cream from demand and generated by-products
    animal_prod_demand = animal_prod_demand[animal_prod_demand.index.get_level_values('animal_prod') != 'cream']
    animal_by_products = animal_by_products[animal_by_products.index.get_level_values('by_prod')!='cream']

    return (animal_prod_demand, animal_by_products)