import warnings
import pandas as pd
import numpy as np
from typing import TYPE_CHECKING

from ..utils.verbose_print import verbose_init
from ..utils.misc import fix_herds

if TYPE_CHECKING:
    from CIBUSmod.main_modules.demand_and_conversions import DemandAndConversions
    from CIBUSmod.utils.retriever import ParameterRetriever

class ByProductMgmt():

    '''Management module that handles by-products by allocating residual by-products with no demand to waste management or exports
    and by inducing imports of by-products if necessary to meet demand.

    Parameters
    ----------
    demand : DemandAndConversions object
    herds : pandas.Series of AnimalHerd objects
    par : ParameterRetriever object

    '''

    def __init__(
            self,
            demand : "DemandAndConversions",
            herds : pd.Series,
            par : "ParameterRetriever"
    ):

        self.par = par

        self.demand = demand
        self.herds = fix_herds(herds)

    def calculate(self, verbose=False):

        if 'ByProductMgmt' in self.demand.data_attr.metadata['by_prod_demand']['orig']:

            # Abort calculations and warn if method has already been run.
            # Running it more than once will produce faulty results.
            warnings.warn("ByProductMgmt: Aborting calculations as ByProductMgmt.calculate() has already been run. Run DemandAndConversions.calculate() before running it again.")
            return None

        # Define functions to print progress messages if verbose==True
        vprint = verbose_init(verbose, id_str='ByProductMgmt')

        vprint('Inducing imports of by-products to cover demand ...') # ------------------------------>

        # Get produced by-products
        prod = self.demand.data_attr.get('by_products')

        if isinstance(prod, pd.Series):
            # Make dataframe with 'origin' column
            prod = (
                self.demand.data_attr.get('by_products')
                .rename('domestic')
                .to_frame()
                .rename_axis('origin', axis=1)
            )

        # Get demand for food, non-food and exports
        food_demand = self.demand.data_attr.get('by_prod_demand').copy()

        # Get demand for feed
        feed_demand = (
            pd.concat([h.data_attr.get('feed.by_product_demand').sum() for h in self.herds if 'feed.by_product_demand' in h.data_attr])
            .groupby(['prod_system', 'by_prod']).sum().rename('feed')
        )

        # Combine demand
        total_demand = pd.concat([food_demand, feed_demand], axis=1).fillna(0).sort_index()

        # Get index union
        idx_uni = prod.index.union(total_demand.index)

        # Reindex frames
        prod = prod.reindex(idx_uni).fillna(0)
        total_demand = total_demand.reindex(idx_uni).fillna(0)

        # Calculate induced imports
        induced_imports = (-prod.sum(axis=1).sub(total_demand.sum(axis=1), axis=0)).clip(0)

        # Add induced imports to prod data frame
        prod['imported'] = 0
        prod.loc[:,'imported'] = prod.loc[:,'imported'].add(induced_imports, fill_value=0)

        vprint('Allocating residual by-products to waste management and exports ...') # --------------------->

        # Calculate surplus by-products
        surplus = prod.sum(axis=1).sub(total_demand.sum(axis=1))

        # Calculate share going to export
        surplus_to_export = (
            surplus * (self.par.get('surplus_to_export', **surplus.index.to_frame().to_dict('list'))/100)
        ).replace({0:np.nan}).dropna()

        # Calculate share going to waste
        surplus_to_waste = (
            surplus.sub(surplus_to_export, fill_value=0)
        ).replace({0:np.nan}).dropna()

        # Add induced exports to demand
        food_demand = food_demand.add(surplus_to_export.rename('export').to_frame(), fill_value=0).fillna(0).reindex(food_demand.columns, axis=1)

        # Update data attributes
        self.demand.data_attr.add(
            food_demand,
            name = 'by_prod_demand',
            unit = self.demand.data_attr.metadata['by_prod_demand']['unit'],
            orig = "DemandAndConversions >> ByProductMgmt",
            desc = " Demand for by-products >> Updated with induced export of surplus by-products"
        )
        self.demand.data_attr.add(
            prod,
            name = 'by_products',
            unit = self.demand.data_attr.metadata['by_products']['unit'],
            orig = "Demand for by-products >> ByProductMgmt",
            desc = "Generated by-products >> Updated with induced imports"
        )

        # Store by-products going to waste as new data attribute
        self.demand.data_attr.add(
            surplus_to_waste,
            name = 'by_prod_to_waste',
            unit = 'kg/year',
            orig = "ByProductMgmt",
            desc = "Generated by-products going to waste treatment"
        )

        vprint(type='end')

        return None
