import warnings
import pandas as pd
import numpy as np

from ..utils.verbose_print import verbose_init
from ..utils.misc import rgetattr, rsetattr
from ..utils.misc import multiindex_to_dict
from ..utils.retriever import ParameterRetriever

ixsl = pd.IndexSlice

class Diet(object):
    '''Class that calculates demand for domestic and imported crop and animal products, as well as generated food waste
    and by-products etc. A per capita diet is defined in the parameter Excel sheet along with parmeters for import shares,
    conversion factors, waste levels, etc.

    Parameters
    ----------
    par : ParameterRetriever object

    Attributes set on init
    ----------------------
    None

    Attributes set by FoodDemand.calculate()
    ----------------------------------------
    population : int [millions]
    food_demand : pandas.DataFrame [kg/year]
        Demand for food per production system and origin (domestic, imported)
    food_demand_to_processing : pandas.DataFrame [kg/year]
        Food demand after accounting for household, retail and processing wastes
    crop_prod_demand : pandas.DataFrame
    crop_by_products : pandas.DataFrame
    animal_prod_demand : pandas.DataFrame
    animal_by_products : pandas.DataFrame
    waste : pandas.DataFrame [kg/year]
        Generated waste at household, retail and processing. Only includes domestically
        generated waste assuming that processing waste for imported foods occur abroad.
    '''

    # List of attributes in class
    # Note: remember to update if more attributes are included!
    data_attr = ['population','food_demand','waste']

    def __init__(self, par: ParameterRetriever):
        self.par = par

    def calculate(self, verbose=False):
        '''Calculate crop and animal product demand and generated by-products and waste
        
        Parameters
        ----------
        verbose : Bool
            Whether or not to print progress messages
            
        Returns
        -------
        Nothing. Stores output in pandas.DataFrames in the attrubutes:
        'food_demand', 'crop_prod_demand', 'animal_prod_demand', 'by_products' and 'waste'
        '''

        # Define functions to print progress messages if verbose==True
        vprint = verbose_init(verbose, id_str='Diet')

        # Get population size
        self.population = self.par.get('population')[0]

        # Calculate total food demand [kg/year]
        vprint('Calculating food demand ...')
        self.calculate_food_demand()

        # Calculate generated food waste [kg/year]
        vprint('Calculating waste ...')
        self.calculate_waste()

        # Calculate demand for crop products and generated crop by-products
        vprint('Calculating crop product demand ...')
        self.calculate_crop_product_demand()

        # Calculate demand for animal products and generated animal by-products
        vprint('Calculating crop product demand ...')
        self.calculate_animal_product_demand()

        vprint(type='end')

    def calculate_food_demand(self):
        
        # Get food items included in the diet and included production systems
        foods = self.par.get_unique('food', 'parameter == "consumption"')
        prod_systems = self.par.get_unique('prod_system', 'parameter == "share_in_prod_system"')

        # Create dataframe for domestic and imported food demand ('food_demand')
        food_demand = pd.DataFrame(
            columns=pd.Index(['domestic','imported'],name='origin'),
            index=pd.MultiIndex.from_tuples(
                [(f,ps) for f in foods for ps in prod_systems],
                names=['food','prod_system']
            )
        )

        # Get shares per production system
        share_per_prod_system = self.par.get_from_frame('share_in_prod_system',food_demand)/100
        # Calculate share conventional as what remains (Note: important that 'share_in_prod_system' == -100 in parameter Excel sheet)
        share_con = share_per_prod_system.loc[(slice(None),'conventional'),:]
        share_con = (share_per_prod_system.groupby('food').sum() * -1).reindex(share_con.index, level='food')
        share_per_prod_system.update(share_con)

        # Get shares per origin
        share_per_origin = self.par.get_from_frame('share_imported',food_demand)/100
        share_per_origin.loc[:,'domestic'] = 1 - share_per_origin.loc[:,'imported']

        # Get consumption (g/day)
        cons = self.par.get_from_frame('consumption',food_demand) * share_per_prod_system * share_per_origin
        # Convert to [kg/year] and factor in population
        self.par.clear()
        self.food_demand = cons / 1000 * 365.25 * self.population * 1000000

        self.par.clear()

    def calculate_waste(self):
        
        # Get shares wasted at different levels
        waste_shares = pd.DataFrame(
            columns = pd.Index(['household','retail','processing'], name='waste_level'),
            index = self.food_demand.index
        )
        rel = self.par.get_rel('food','food_group')
        waste_shares['food_group'] = [rel[f] for f in waste_shares.index.get_level_values('food')]
        waste_shares.set_index('food_group', append=True, inplace=True)
        waste_shares = self.par.get_from_frame('waste_share',waste_shares)/100

        # Apply waste shares and calculate food needed to enter each stage
        food_to_household = self.food_demand.mul(1/(1-waste_shares['household']),axis=0)
        food_to_retail = food_to_household.mul(1/(1-waste_shares['retail']),axis=0)
        food_to_processing = food_to_retail.mul(1/(1-waste_shares['processing']),axis=0)

        # Create waste dataframe
        waste = pd.DataFrame(
            columns=waste_shares.columns,
            index=waste_shares.index
        )

        # Calculate waste at each stage
        # Processing waste for imported foods is assumed to be generated abroad (i.e. not included)
        waste['household'] = (food_to_household - self.food_demand).sum(axis=1)
        waste['retail'] = (food_to_retail - food_to_household).sum(axis=1)
        waste['processing'] = food_to_processing['domestic'] - food_to_retail['domestic'] 
        waste = waste.droplevel('food_group')

        self.food_demand_to_processing = food_to_processing
        self.waste = waste

        self.par.clear()

    def calculate_crop_product_demand(self):
        
        # Get crop products
        cps = self.par.get_unique('crop_prod','parameter == "conv_factor" & f_species.isna()')
        bps = self.par.get_unique('by_prod','parameter == "conv_factor" & f_species.isna()')

        # Create dataframe for crop product demand
        crop_prod_demand = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(o,cp) for o in self.food_demand_to_processing.columns for cp in cps],
                names=['origin','crop_prod']
            ),
            index = self.food_demand_to_processing.index
        )

        # Create dataframe for generated by-products
        crop_by_products = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(o,cp,bp) for (o,cp) in crop_prod_demand.columns for bp in bps],
                names=['origin','crop_prod','by_prod']
            ),
            index = self.food_demand_to_processing.index
        )

        # Get conversion factors. 0 are replaced with NaN to avoid div by 0
        # NaNs are later replaced with 0s
        CF_crop_prod = (self.par.get_from_frame('conv_factor', crop_prod_demand)/100).replace({0:np.nan})
        CF_by_prod = (self.par.get_from_frame('conv_factor', crop_by_products)/100).replace({0:np.nan})

        # Calculate demand for crop products and generated by-products
        crop_prod_demand = (self.food_demand_to_processing / CF_crop_prod).fillna(0)
        crop_by_products = (self.food_demand_to_processing * CF_by_prod).fillna(0)

        # Store dataframes and drop rows with all 0s
        self.crop_prod_demand = crop_prod_demand.loc[(crop_prod_demand!=0).any(axis=1)]
        self.crop_by_products = crop_by_products.loc[(crop_by_products!=0).any(axis=1)]

    def calculate_animal_product_demand(self):
        self.animal_product_demand = None
        self.animal_by_products = None

        # Handle dairy

        # Handle demand for animal by-products
