import warnings
import pandas as pd
import numpy as np

from ..utils.verbose_print import verbose_init
from ..utils.misc import rgetattr, rsetattr
from ..utils.misc import multiindex_to_dict
from ..utils.retriever import ParameterRetriever

ixsl = pd.IndexSlice

class Diet(object):
    '''Class that calculates demand for domestic and imported crop and animal products, as well as generated food waste
    and by-products etc. A per capita diet is defined in the parameter Excel sheet along with parmeters for import shares,
    conversion factors, waste levels, etc.

    Parameters
    ----------
    par : ParameterRetriever object

    Attributes set on init
    ----------------------
    None

    Attributes set by FoodDemand.calculate()
    ----------------------------------------
    population : int [millions]
    food_demand : pandas.DataFrame [kg/year]
        Demand for food per production system and origin (domestic, imported)
    food_demand_to_processing : pandas.DataFrame [kg/year]
        Food demand after accounting for household, retail and processing wastes
    crop_prod_demand : pandas.DataFrame
    crop_by_products : pandas.DataFrame
    animal_prod_demand : pandas.DataFrame
    animal_by_products : pandas.DataFrame
    waste : pandas.DataFrame [kg/year]
        Generated waste at household, retail and processing. Only includes domestically
        generated waste assuming that processing waste for imported foods occur abroad.
    '''

    # List of attributes in class
    # Note: remember to update if more attributes are included!
    data_attr = ['population','food_demand','waste']

    def __init__(self, par: ParameterRetriever):
        self.par = par

    def calculate(self, verbose=False):
        '''Calculate crop and animal product demand and generated by-products and waste
        
        Parameters
        ----------
        verbose : Bool
            Whether or not to print progress messages
            
        Returns
        -------
        Nothing. Stores output in pandas.DataFrames in the attrubutes:
        'food_demand', 'crop_prod_demand', 'animal_prod_demand', 'by_products' and 'waste'
        '''

        # Define functions to print progress messages if verbose==True
        vprint = verbose_init(verbose, id_str='Diet')

        # Get population size
        self.population = self.par.get('population')[0]

        # Calculate total food demand [kg/year]
        vprint('Calculating food demand ...')
        self.calculate_food_demand()

        # Calculate generated food waste [kg/year]
        vprint('Calculating waste ...')
        self.calculate_waste()

        # Calculate demand for crop products and generated crop by-products
        vprint('Calculating crop product demand ...')
        self.calculate_crop_product_demand()

        # Calculate demand for animal products and generated animal by-products
        vprint('Calculating crop product demand ...')
        self.calculate_animal_product_demand()

        vprint(type='end')

    def calculate_food_demand(self):
        
        # Get food items included in the diet and included production systems
        foods = self.par.get_unique('food', 'parameter == "consumption"')
        prod_systems = self.par.get_unique('prod_system', 'parameter == "share_in_prod_system"')

        # Create dataframe for domestic and imported food demand ('food_demand')
        food_demand = pd.DataFrame(
            columns=pd.Index(['domestic','imported'],name='origin'),
            index=pd.MultiIndex.from_tuples(
                [(f,ps) for f in foods for ps in prod_systems],
                names=['food','prod_system']
            )
        )

        # Get shares per production system
        share_per_prod_system = self.par.get_from_frame('share_in_prod_system',food_demand)/100
        # Calculate share conventional as what remains (Note: important that 'share_in_prod_system' == -100 in parameter Excel sheet)
        share_con = share_per_prod_system.loc[(slice(None),'conventional'),:]
        share_con = (share_per_prod_system.groupby('food').sum() * -1).reindex(share_con.index, level='food')
        share_per_prod_system.update(share_con)

        # Get shares per origin
        share_per_origin = self.par.get_from_frame('share_imported',food_demand)/100
        share_per_origin.loc[:,'domestic'] = 1 - share_per_origin.loc[:,'imported']

        # Get consumption (g/day)
        cons = self.par.get_from_frame('consumption',food_demand) * share_per_prod_system * share_per_origin
        # Convert to [kg/year] and factor in population
        self.par.clear()
        self.food_demand = cons / 1000 * 365.25 * self.population * 1000000

        self.par.clear()

    def calculate_waste(self):
        
        # Get shares wasted at different levels
        waste_shares = pd.DataFrame(
            columns = pd.Index(['household','retail','processing'], name='waste_level'),
            index = self.food_demand.index
        )
        rel = self.par.get_rel('food','food_group')
        waste_shares['food_group'] = [rel[f] for f in waste_shares.index.get_level_values('food')]
        waste_shares.set_index('food_group', append=True, inplace=True)
        waste_shares = self.par.get_from_frame('waste_share',waste_shares)/100

        # Apply waste shares and calculate food needed to enter each stage
        food_to_household = self.food_demand.mul(1/(1-waste_shares['household']),axis=0)
        food_to_retail = food_to_household.mul(1/(1-waste_shares['retail']),axis=0)
        food_to_processing = food_to_retail.mul(1/(1-waste_shares['processing']),axis=0)

        # Create waste dataframe
        waste = pd.DataFrame(
            columns=waste_shares.columns,
            index=waste_shares.index
        )

        # Calculate waste at each stage
        # Processing waste for imported foods is assumed to be generated abroad (i.e. not included)
        waste['household'] = (food_to_household - self.food_demand).sum(axis=1)
        waste['retail'] = (food_to_retail - food_to_household).sum(axis=1)
        waste['processing'] = food_to_processing['domestic'] - food_to_retail['domestic'] 
        waste = waste.droplevel('food_group')

        self.food_demand_to_processing = food_to_processing
        self.waste = waste

        self.par.clear()

    def calculate_crop_product_demand(self):
        
        # Get crop products and by-products
        cps = self.par.get_unique('crop_prod','parameter == "conv_factor_main"')
        bps = self.par.get_unique(['crop_prod','by_prod'],'parameter == "conv_factor_by"')

        # Create dataframe for crop product demand
        crop_prod_demand = pd.DataFrame(
            columns = pd.Index(cps, name='crop_prod'),
            index = self.food_demand_to_processing.index
        )

        # Create dataframe for generated by-products
        crop_by_products = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(cp,bp) for cp,bp in bps.values],
                names=['crop_prod','by_prod']
            ),
            index = self.food_demand_to_processing.index
        )

        # Get conversion factors. 0 are replaced with NaN to avoid div by 0
        # NaNs are later replaced with 0s
        CF_crop_prod = (self.par.get_from_frame('conv_factor_main', crop_prod_demand)/100).replace({0:np.nan})
        CF_by_prod = (self.par.get_from_frame('conv_factor_by', crop_by_products)/100).replace({0:np.nan})

        # Calculate demand for crop products and generated by-products
        crop_prod_demand = (1 / CF_crop_prod).mul(self.food_demand_to_processing['domestic'], axis=0).fillna(0)
        crop_by_products = (CF_by_prod).mul(self.food_demand_to_processing['domestic'], axis=0).fillna(0)

        # Aggregate
        crop_prod_demand = crop_prod_demand.stack('crop_prod').groupby(['prod_system','crop_prod']).sum()
        crop_by_products = crop_by_products.stack(['crop_prod','by_prod']).groupby(['prod_system','crop_prod','by_prod']).sum()

        # Store dataframes
        self.crop_prod_demand = crop_prod_demand
        self.crop_by_products = crop_by_products

        self.par.clear()

    def calculate_animal_product_demand(self):

        # Get animal products and by-products
        aps = self.par.get_unique(['species','animal_prod'],'parameter == "conv_factor_main" & ~f_species.isna()')
        bps = self.par.get_unique(['species','animal_prod','by_prod'],'parameter == "conv_factor_by"')

        # Create dataframe for animal product demand
        animal_prod_demand = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(sp,ap) for sp,ap in aps.values],
                names=['species','animal_prod']
            ),
            index = self.food_demand_to_processing.index
        )

        # Create dataframe for generated by-products
        animal_by_products = pd.DataFrame(
            columns = pd.MultiIndex.from_tuples(
                [(sp,ap,bp) for sp,ap,bp in bps.values],
                names=['species','animal_prod','by_prod']
            ),
            index = self.food_demand_to_processing.index
        )

        # Get conversion factors. 0 are replaced with NaN to avoid div by 0
        # NaNs are later replaced with 0s
        CF_animal_prod = (self.par.get_from_frame('conv_factor_main', animal_prod_demand)/100).replace({0:np.nan})
        CF_by_prod = (self.par.get_from_frame('conv_factor_by', animal_by_products)/100).replace({0:np.nan})

        # Calculate demand for animal products and generated by-products
        animal_prod_demand = (1 / CF_animal_prod).mul(self.food_demand_to_processing['domestic'], axis=0).fillna(0)
        animal_by_products = (CF_by_prod).mul(self.food_demand_to_processing['domestic'], axis=0).fillna(0)

        # Aggregate
        animal_prod_demand = animal_prod_demand.stack(['species','animal_prod']).groupby(['prod_system','species','animal_prod']).sum()
        animal_by_products = animal_by_products.stack(['species','animal_prod','by_prod']).groupby(['prod_system','species','animal_prod','by_prod']).sum()

        # Handle dairy "cream balance". As consumption of high fat dairy products and associated demand for cream exceeds
        # the ammount of cream generated from consumption of low fat dairy products this induces an export of low fat
        # dairy products.
        #
        # Note: The method currently implemented will fail to handle a situation where the opposite is true, i.e. where
        # consumption of low fat products generates more cream than needed to cover consumption of high fat products.
        self.par.clear()
        cream_to_raw_milk = 1/(self.par.get(
            'conv_factor_by',
            food='Milk and products 1-2% fat',
            species='cattle',
            animal_prod='milk',
            by_prod='cream'
        )[0]/100)

        self.par.clear()
        raw_milk_to_skim_milk = self.par.get(
            'conv_factor_main',
            food='Milk and products 1-2% fat',
            species='cattle',
            animal_prod='milk'
        )[0]/100

        # Calculate shortage of cream to satisfy demand for fat rich products
        cream_shortage = \
        animal_prod_demand.loc[(slice(None),'cattle','cream')] - \
        animal_by_products.loc[(slice(None),'cattle','milk','cream')]

        # Calculate additional raw milk that needs to be produced and induced skim milk exports
        add_raw_milk_prod = cream_shortage * cream_to_raw_milk
        induced_skim_milk_exports = add_raw_milk_prod * raw_milk_to_skim_milk

        # Add additional raw milk production to demand dataframe
        for ps in animal_prod_demand.index.get_level_values('prod_system').unique():
            animal_prod_demand.loc[(ps,'cattle','milk')] = \
            animal_prod_demand.loc[(ps,'cattle','milk')] + \
            add_raw_milk_prod[ps]

        # The "cream balance" is now handled. So, drop cream from demand and generated by-products
        animal_prod_demand = animal_prod_demand[animal_prod_demand.index.get_level_values('animal_prod') != 'cream']
        animal_by_products = animal_by_products[animal_by_products.index.get_level_values('by_prod')!='cream'].rename({'cream':'milk'})

        # Store dataframes
        self.animal_prod_demand = animal_prod_demand
        self.animal_by_products = animal_by_products
        self.induced_skim_milk_exports = induced_skim_milk_exports # A bit temporary... find a good way to handle this!!!

        # Handle demand for animal by-products !!!
