import warnings
import pandas as pd
import numpy as np

from ..utils.verbose_print import verbose_init
from ..utils.misc import rgetattr, rsetattr
from ..utils.misc import multiindex_to_dict
from ..utils.retriever import ParameterRetriever

ixsl = pd.IndexSlice

class Diet(object):
    '''Class that calculates demand for domestic and imported crop and animal products, as well as generated food waste
    and by-products etc. A per capita diet is defined in the parameter Excel sheet along with parmeters for import shares,
    conversion factors, waste levels, etc.

    Parameters
    ----------
    par : ParameterRetriever object

    Attributes set on init
    ----------------------
    None

    Attributes set by FoodDemand.calculate()
    ----------------------------------------
    population : int
    food_demand : pandas.DataFrame
    crop_prod_demand : pandas.DataFrame
    animal_prod_demand : pandas.DataFrame
    by_products : pandas.DataFrame
    waste : pandas.DataFrame


    '''

    # List of attributes in class
    # Note: remember to update if more attributes are included!
    data_attr = []

    def __init__(self, par: ParameterRetriever):
        self.par = par

    def calculate(self, verbose=False):
        '''Calculate crop and animal product demand and generated by-products and waste
        
        Parameters
        ----------
        verbose : Bool
            Whether or not to print progress messages
            
        Returns
        -------
        Nothing. Stores output in pandas.DataFrames in the attrubutes:
        'food_demand', 'crop_prod_demand', 'animal_prod_demand', 'by_products' and 'waste'
        '''

        # Get population size
        self.population = self.par.get('population')[0]

        # Calculate total food demand [kg/year]
        self.calculate_food_demand()

    def calculate_food_demand(self):
        # Get food items included in the diet and included production systems
        foods = self.par.get_unique('food', 'parameter == "consumption"')
        prod_systems = self.par.get_unique('prod_system', 'parameter == "share_in_prod_system"')

        # Create dataframe for domestic and imported food demand ('food_demand')
        food_demand = pd.DataFrame(
            columns=pd.Index(['domestic','imported'],name='origin'),
            index=pd.MultiIndex.from_tuples(
                [(f,ps) for f in foods for ps in prod_systems],
                names=['food','prod_system']
            )
        )

        # Get shares per production system
        share_per_prod_system = self.par.get_from_frame('share_in_prod_system',food_demand)/100
        # Calculate share conventional as what remains (Note: important that 'share_in_prod_system' == -100 in parameter Excel sheet)
        share_con = share_per_prod_system.loc[(slice(None),'conventional'),:]
        share_con = (share_per_prod_system.groupby('food').sum() * -1).reindex(share_con.index, level='food')
        share_per_prod_system.update(share_con)

        # Get shares per origin
        share_per_origin = self.par.get_from_frame('share_imported',food_demand)/100
        share_per_origin.loc[:,'domestic'] = 1 - share_per_origin.loc[:,'imported']

        # Get consumption (g/day)
        cons = self.par.get_from_frame('consumption',food_demand) * share_per_prod_system * share_per_origin
        # Convert to [kg/year] and factor in population
        self.par.clear()
        self.food_demand = cons / 1000 * 365.25 * self.population * 1000000


